openapi: 3.0.3
info:
  title: ops-service
  version: 0.1.0
  description: Ops tasking API for GroundOps GPL showcase.
servers:
  - url: http://localhost:8081
security:
  - bearerAuth: []
paths:
  /api/tasks:
    get:
      summary: List tasking tickets
      responses:
        '200':
          description: Task list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskResponse'
  /api/tasks/{taskId}:
    get:
      summary: Get task detail
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '404':
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    TaskResponse:
      type: object
      required: [id, planId, asset, windowStart, windowEnd, priority, status, createdBy, createdAt]
      properties:
        id:
          type: string
        planId:
          type: string
        asset:
          type: string
        windowStart:
          type: string
          format: date-time
        windowEnd:
          type: string
          format: date-time
        priority:
          type: string
        status:
          type: string
        createdBy:
          type: string
        createdAt:
          type: string
          format: date-time
        correlationId:
          type: string
    ProblemDetail:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        correlationId:
          type: string
